os: linux
dist: xenial
sudo: false
language: generic
services:
  - docker

env: DOCKER_IMAGE=conanio/gcc8

script:
  - docker run --rm -v "$TRAVIS_BUILD_DIR":/home/conan "$DOCKER_IMAGE" bash -c ./travis.sh

