os: linux
dist: xenial
sudo: required
language: cpp
services:
   - docker

env: DOCKER_IMAGE=conanio/gcc8

script:
  - pwd
  - cmake --version
  - g++ --version
  - rm -rf build && mkdir -p build && cd build
  - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build
  - ctest

